version: '3'
services:
  nginx:
    image: nginx:stable
    ports:
      - '80:80'
      - '18001:18001'
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./static:/usr/share/nginx/html
      - ./webase:/usr/local/webase
      - ./logs:/var/log/nginx
