# 比较通用的nginx 
version: '3'
services:
  nginx:
    image: nginx:stable
    ports:
      - '80:80'
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
