version: '3'
services:
  nginx:
    image: 10.110.197.137/letms-ppraise/letms-ppraise-web:v1.0
    ports:
      - '80:80'
    restart: always
    privileged: true
    environment:
        TZ : 'Asia/Shanghai'
    volumes:
      - /etc/localtime:/etc/localtime
#      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginxFile:/usr/local/file
      - ./config.json:/usr/share/nginx/html/config.json
      - ./nginxLogs:/var/log/nginx

