name: work-study
version: '3'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/edu-lenovo-product/letms-ppraise-web:v1.0
    ports:
      - '443:443'
      - '80:80'
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
#      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginxFile:/usr/local/file
      - ./https:/usr/https
      - ./config.json:/usr/share/nginx/html/config.json
      - ./nginxLogs:/var/log/nginx 

